// Re-export Lucide icons under the names used throughout the workbench.
// All consumers import from this file; only this file touches lucide-react.
export {
  Copy as CopyIcon,
  Download as DownloadIcon,
  FolderOpen as FolderOpenIcon,
  File as FileIcon,
  Grid2x2 as GridIcon,
  Hand as HandIcon,
  ScanSearch as InspectIcon,
  Languages as LanguageIcon,
  Moon as MoonIcon,
  Pencil as PencilIcon,
  MousePointer2 as PointerIcon,
  Search as SearchIcon,
  Sun as SunIcon,
  Type as TypeIcon,
  ArrowUpRight as VectorIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
  Maximize2 as FitIcon,
  RotateCcw as ResetIcon,
  Save as SaveIcon,
  PanelRight as PanelIcon,
  Settings as SettingsIcon,
} from 'lucide-react';
